#!/usr/bin/env bash
# tools/scripts/build-agents.sh
# Assembles L0-L4 template files into per-tool system prompt formats.
# Tags: [agents, build, system-prompt, claude-code, opencode, assembly]
#
# Usage:
#   ./build-agents.sh [agent-name]         # build one agent
#   ./build-agents.sh                      # build all agents
#
# Output per agent (in agents/{name}/):
#   CLAUDE.md          → Claude Code (auto-injected from cwd)
#   system-prompt.md   → Universal (opencode, qwencode, any tool)
#
# L0-L4 Load Order:
#   agents/_template/L0-identity.md      → Base identity (overridden by agent-specific)
#   agents/_template/L1-cognition.md     → OTAA cycle (shared)
#   agents/_template/L2-memory-config.yaml → Memory config (shared)
#   agents/_template/L3-mcp-tools.json  → Tool whitelist (overridden per agent)
#   agents/_template/L4-guardrails.yaml  → Execution limits (shared)
#   rules/global-constitution.md         → Global law
#   rules/position-descriptions/{role}-pd.md → Role-specific mandate
#
# Tool-specific notes:
#   Claude Code:  reads CLAUDE.md from cwd and all parent dirs automatically.
#                 Use `claude --cwd agents/{name}` or cd into the agent dir.
#   opencode:     set system_prompt_file in .opencode/config.json
#   qwencode:     paste contents of system-prompt.md into system prompt field
#   Generic:      any tool that accepts a --system-prompt file flag

set -euo pipefail

NOSPACE_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
AGENTS_DIR="${NOSPACE_ROOT}/agents"
TEMPLATE_DIR="${AGENTS_DIR}/_template"
RULES_DIR="${NOSPACE_ROOT}/rules"

KNOWN_AGENTS=(
  assistant
  cto
  tech-lead
  senior-architect
  qa-lead
  devops-lead
  sre-lead
  reviewer-agent
  research-assistant
)

# ---

build_agent() {
  local name="$1"
  local agent_dir="${AGENTS_DIR}/${name}"
  local pd_file="${RULES_DIR}/position-descriptions/${name}-pd.md"

  if [[ ! -d "${agent_dir}" ]]; then
    echo "[SKIP] ${name}: directory not found at ${agent_dir}"
    return
  fi

  echo "[BUILD] ${name}..."

  # Resolve L0: agent-specific override or template
  local l0="${agent_dir}/L0-identity.md"
  [[ ! -f "${l0}" ]] && l0="${TEMPLATE_DIR}/L0-identity.md"

  local l1="${TEMPLATE_DIR}/L1-cognition.md"
  local l2="${TEMPLATE_DIR}/L2-memory-config.yaml"
  local l3="${agent_dir}/L3-mcp-tools.json"
  [[ ! -f "${l3}" ]] && l3="${TEMPLATE_DIR}/L3-mcp-tools.json"
  local l4="${TEMPLATE_DIR}/L4-guardrails.yaml"

  local constitution="${RULES_DIR}/global-constitution.md"

  # ---
  # Build system-prompt.md (universal format)
  # ---
  local out="${agent_dir}/system-prompt.md"
  {
    echo "<!-- AUTO-GENERATED by tools/scripts/build-agents.sh — DO NOT EDIT MANUALLY -->"
    echo "<!-- Agent: ${name} | Built: $(date -u +%Y-%m-%dT%H:%M:%SZ) -->"
    echo ""
    echo "# AGENT SYSTEM PROMPT: ${name}"
    echo ""
    echo "---"
    echo "## LAYER 0 — IDENTITY"
    echo ""
    cat "${l0}"
    echo ""
    echo "---"
    echo "## LAYER 1 — COGNITIVE LOOP"
    echo ""
    cat "${l1}"
    echo ""
    echo "---"
    echo "## LAYER 2 — MEMORY CONFIG"
    echo ""
    echo '```yaml'
    cat "${l2}"
    echo '```'
    echo ""
    echo "---"
    echo "## LAYER 3 — TOOL WHITELIST"
    echo ""
    echo '```json'
    cat "${l3}"
    echo '```'
    echo ""
    echo "---"
    echo "## LAYER 4 — GUARDRAILS"
    echo ""
    echo '```yaml'
    cat "${l4}"
    echo '```'
    echo ""
    echo "---"
    echo "## GLOBAL CONSTITUTION"
    echo ""
    cat "${constitution}"

    if [[ -f "${pd_file}" ]]; then
      echo ""
      echo "---"
      echo "## POSITION DESCRIPTION"
      echo ""
      cat "${pd_file}"
    fi
  } > "${out}"

  # ---
  # Build CLAUDE.md (Claude Code native format)
  # Uses @-import syntax when supported; falls back to full inline.
  # ---
  local claude_out="${agent_dir}/CLAUDE.md"
  {
    echo "<!-- AUTO-GENERATED by tools/scripts/build-agents.sh -->"
    echo "<!-- Claude Code reads this file automatically from the agent's cwd. -->"
    echo ""
    echo "# ${name} — Agent Context"
    echo ""
    echo "Full system prompt is in [system-prompt.md](./system-prompt.md)."
    echo ""
    echo "> If your Claude Code version supports @-imports, replace the line below"
    echo "> with: @system-prompt.md"
    echo ""
    echo "---"
    echo ""
    cat "${out}"
  } > "${claude_out}"

  echo "[DONE] ${name}: system-prompt.md + CLAUDE.md written to ${agent_dir}/"
}

# ---

main() {
  if [[ $# -gt 0 ]]; then
    build_agent "$1"
  else
    for agent in "${KNOWN_AGENTS[@]}"; do
      build_agent "${agent}"
    done
  fi
  echo ""
  echo "Build complete."
  echo ""
  echo "Claude Code usage:  cd agents/{name} && claude"
  echo "opencode usage:     set system_prompt_file = agents/{name}/system-prompt.md"
  echo "Universal:          cat agents/{name}/system-prompt.md | <tool> --system-prompt -"
}

main "$@"
