import { drizzle } from "drizzle-orm/d1";
import type { DrizzleD1Database } from "drizzle-orm/d1";

// Per-request D1 database factory
// D1 binding is only available per-request in CF Workers
export function createKbDb(d1: D1Database): DrizzleD1Database {
  return drizzle(d1);
}

export function createAuthDb(d1: D1Database): DrizzleD1Database {
  return drizzle(d1);
}

// Helper to get bindings from request event
export function getBindings(event: any): Env {
  const bindings = event.context?.bindings ?? event.context?.cloudflare?.env;
  if (!bindings) {
    throw new Error("CF bindings not available. Run with wrangler pages dev or deploy to CF Pages.");
  }
  return bindings as Env;
}

// Env type — matches wrangler.toml bindings
// Full type generated by `wrangler types` → worker-configuration.d.ts
interface Env {
  KB_DB: D1Database;
  AUTH_DB: D1Database;
  HARKLY_R2: R2Bucket;
  OAUTH_KV: KVNamespace;
  AUTH_KV: KVNamespace;
  SESSION_KV: KVNamespace;
  VECTORIZE_INDEX: VectorizeIndex;
  INGEST_QUEUE: Queue;
  AI: Ai;
}
