services:
  freqtrade:
    image: freqtradeorg/freqtrade:stable
    container_name: nomos-freqtrade
    restart: unless-stopped
    volumes:
      - ./user_data:/freqtrade/user_data
      - ./config.json:/freqtrade/config.json
    ports:
      - "8080:8080"
    command: trade --dry-run --config /freqtrade/config.json --strategy NomosBasicStrategy -vv
